
# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
# set -g @dracula-ssh-session-colors "dark_gray black"

# set -s default-terminal 'tmux-256color'
# unbind C-Left
# unbind C-Right
# unbind M-Left
# unbind M-Right

set -g mouse on
set-window-option -g xterm-keys on
#
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode MouseDragEnd1Pane
bind -T copy-mode-vi y send -X copy-pipe "reattach-to-user-namespace pbcopy"\; display-message "copied to system clipboard"
# set -g @plugin 'dracula/tmux'
#
# set -g @dracula-plugins "ssh-session git cpu-usage weather time"
# set -g @dracula-show-empty-plugins false
# set -s default-terminal 'xterm-kitty'
run '~/.tmux/plugins/tpm/tpm'
